config/routes.rb
Tumblrdomains::Application.routes.draw do
  
  resources :registrations do
    member do
      get :choose_tumblelog
    end

    collection do
      post :set_tumblelog
    end
  end

  match 'check_availability', :to => 'domains#check_availability', :as => 'check_availability'
  
  match '/payments/create', :to => 'payments#create', :as => 'payment_callback'

  match '/thank_you', :to => 'payments#thank_you', :as => 'payment_complete'
  match '/payment_problem', :to => 'payments#problem', :as => 'payment_problem'
  match '/registration_problem', :to => 'payments#registration_problem', :as => 'registration_problem'

  root :to => 'home#index'
end

app/models/registration.rb
class Registration < ActiveRecord::Base

  validates :password, :presence => true
  validates :email, :presence => true

  validate :tumblr_login

  after_create :set_tumblelog

  def tumblelogs
    @tumblelogs ||= tumblr_handler.tumblelogs
  end

  def modify_tumblelogs_domain!
    DomainChanger.handler.new(self.tumblelog, self.email, self.password).change_to(self.domain)
  end

  def register!
    handler = Registrar.handler.new(self.domain)
    handler.register!
    
    if handler.success?
      self.update_attribute :dnsimple_id, handler.domain_id
    end

    handler
  end

  def amount
    BigDecimal.new("9.95")
  end

  def reference
    "tumblr-#{id}"
  end

  def reason
    "Register #{self.domain} for Tumblr #{self.tumblelog}"
  end

  private

  def tumblr_login
    unless tumblr_handler.authorized?
      self.errors.add(:base, 'Could not log in to Tumblr.  Please try again.')
    end
  end

  def tumblr_handler
    @tumblr_handler ||= TumblrApi.handler.new(self.email, self.password)
  end

  def set_tumblelog
    if tumblelogs.size == 1
      self.tumblelog = tumblelogs.first['name']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def whois
    @whois ||= Whois::Client.new
  end

  def current_registration
    @current_registration ||= Registration.find_by_id(session[:registration_id])
  end

  def current_registration=(r)
    session[:registration_id] = r.id
    r
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController

  def check_availability
    @answer = whois.query(params[:domain_name])

    respond_to do |format|
      format.js {
        if @answer.available?
          render :json => {:available => true }
        else
          render :json => {:available => false, :error => "Sorry, but #{params[:domain_name]} is not available to register." }
        end
      }
      format.html {
        if @answer.available?
          redirect_to new_registration_path(:domain_name => params[:domain_name])
        else
          redirect_to "/", :error => "Sorry, that domain is not available."
        end
      }
    end
  end

  before_filter :check_empty
  before_filter :check_top_level_domain

  private

  def check_empty
    if params[:domain_name].blank?
      render :json => {:available => false, :error => 'Sorry, but you entered a blank domain name.'} and return false
    end
  end

  def check_top_level_domain
    top_level_domain = params[:domain_name].split('.').last
    unless Registrar.allowable_top_level_domains.include?(top_level_domain)
      render :json => {:available => false, :error => 'Sorry, but we only support .com and .net domain names'} and return false
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home

  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  

  def create

    fps_response = AmazonFPS::CobrandResponse.new(params)

    if fps_response.success?

      payment = AmazonFPS::Pay.new(fps_response.caller_reference, fps_response.token, BigDecimal.new("9.95")).call

      if payment.success?
        registration = current_registration
        
        registration.update_attribute :transaction_id, payment.transaction_id

        registration.modify_tumblelogs_domain!

        handler = registration.register!

        if handler.success?
          redirect_to payment_complete_path
        else
          # background job, retry to register
          redirect_to registration_problem_path, :error => handler.error_message
        end
      else
        # payment.error_message
        redirect_to payment_problem_path, :error => payment.error_message
      end
    else
      redirect_to payment_problem_path, :error => fps_response.error_message
    end

  end

  def thank_you
    @registration = current_registration
  end

  def problem
    @registration = current_registration
  end

  def registration_problem
    @registration = current_registration
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @registration = Registration.new(:domain => params[:domain_name])
  end

  def create
    @registration = Registration.new(params[:registration])

    respond_to do |format|
      if @registration.save
        
        self.current_registration = @registration

        format.html {
          redirect_to choose_tumblelog_registration_path(@registration)
        }
        
        format.js {
          render :json => { :success => true, :tumblelogs => @registration.tumblelogs }
        }
      else
        format.html {
          render :action => :new
        }
        format.js {
          render :json => { :success => false, :errors => @registration.errors }
        }
      end
    end
  end

  def set_tumblelog
    @registration = current_registration

    respond_to do |format|
      if @registration.update_attributes(params[:registration])
        format.js {
          render :json => {:success => true, :payment_url => payment_url(@registration) }
        }
      else
        format.js {
          render :json => {:success => false, :errors => @registration.errors}
        }
      end
    end
  end

  def choose_tumblelog
    @registration = Registration.find(params[:id])
  end

  private

  def payment_url(registration)
    AmazonFPS.cobrand_url(registration.amount, "Recurring", registration.reference, registration.reason, payment_callback_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<div id='step_container'>
  <div id='step_1' class='step'>

    <h3>Step 1: <span class='step_headline'>Check domain name availabilty</span> <span class='success' style='display:none'>✓</span></h3>

    <div class='step_contents'>
      <p class='error' style='display:none'>
      </p>


      <%= form_tag check_availability_path, :method => :get %>
        <%= text_field_tag :domain_name, '', :id => 'domain_name', :placeholder => 'example.com' %>

        <%= image_submit_tag 'go.png', :width => "32px" %>
        <p class='help'>
          We only support .com and .net domain names.
        </p>
      </form>
    </div>

  </div>

  <div id="step_2" class='step'>
    <h3>Step 2: <span class='step_headline'>Authorize your tumblr blog</span> <span class='success' style='display:none'>✓</span></h3>
    
    <div class='step_contents' style='display:none'>
      <%= form_tag registrations_path %>
        <p class='error' style='display:none'>
        </p>
        
        <p>
          <%= label_tag :email, 'Tumblr Email' %>
          <%= text_field_tag :email %>
        </p>

        <p>
          <%= label_tag :password, 'Tumblr Password' %>
          <%= password_field_tag :password %>
        </p>

        <%= hidden_field_tag :domain %>

        <p>
          <%= submit_tag 'Go' %>
        </p>

      </form>

    </div>
    
    <div id="step_2_b" class='sub_step' style='display:none'>

      <%= form_tag set_tumblelog_registrations_path %>
      
        <p>
          <%= label_tag :tumblelog, 'Your Tumblr account has more than 1 blog.  Please choose one now' %>
          <%= select_tag :tumblelog %>
        </p>

        <p>
          <%= submit_tag 'Go' %>
        </p>

      </form>

    </div>

  </div>

  <div id="step_3" class='step'>
    <h3>Step 3: Pay with Amazon.com</h3>

    <div class='step_contents' style='display:none'>
      <a href="" id="payments_url" target="_blank">Pay with Amazon.com</a>
    </div>
  </div>

</div

app/views/layouts/application.html.erb
<!doctype html>  

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame 
       Remove this if you use the .htaccess -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>Custom Tumblr Domains</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <%= csrf_meta_tag %>
  <!--  Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

  <!-- CSS : implied media="all" -->
  <%= stylesheet_link_tag 'style.css?v=2' %>
  <link href='http://fonts.googleapis.com/css?family=Droid+Serif&subset=latin' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag 'modernizr-1.6.min.js' %>

</head>

<body>

  <div id="container">
    <header>
      Custom Tumblr Domains
    </header>
    
    <div id="main">
      <%= yield %>
    </div>
    
    <footer>

    </footer>
  </div> <!--! end of #container -->


  <!-- Javascript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery. fall back to local if necessary -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <script>!window.jQuery && document.write(unescape('%3Cscript src="/javascripts/jquery-1.4.2.min.js"%3E%3C/script%3E'))</script>

  <%= javascript_include_tag "rails.jquery.js", "application.js" %>

  <%= yield :javascripts -%>
  
  <!--[if lt IE 7 ]>
    <script src="/javascripts/dd_belatedpng.js"></script>
    <script> DD_belatedPNG.fix('img, .png_bg'); //fix any <img> or .png_bg background-images </script>
  <![endif]-->


  <!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet 
       change the UA-XXXXX-X to be your site's ID -->
  <script>
   var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
   (function(d, t) {
    var g = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    g.async = true;
    g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g, s);
   })(document, 'script');
  </script>
  
</body>
</html>

app/views/payments/problem.html.erb
<h1>There was an error processing payment from Amazon.com</h1>

<h3><%= flash[:error] %></h3>

app/views/payments/registration_problem.html.erb
<h1>There was an error registering the domain <%= @registration.domain %>:</h1>

<h3><%= flash[:error] %></h3>

<p>
  We will automatically retry in a couple of minutes.  If the problem persists, we will notify you and refund your money.  If you have any questions, contact us at problems@customtumblrdomains.com
</p>

app/views/payments/thank_you.html.erb
<h2>Successfully purchased <%= @registration.domain %></h2>